# Generated by Django 6.0.1 on 2026-07-13 20:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tool_slug', models.CharField(blank=True, default='', max_length=150)),
                ('tool_name', models.CharField(blank=True, default='', max_length=200)),
                ('plan_name', models.CharField(blank=True, default='', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_email', models.EmailField(max_length=254)),
                ('whatsapp', models.CharField(blank=True, default='', max_length=50)),
                ('note', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('path', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(blank=True, default='', max_length=200)),
                ('quote', models.TextField()),
                ('rating', models.IntegerField(default=5)),
                ('avatar_url', models.CharField(blank=True, default='', max_length=500)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('mark', models.CharField(blank=True, default='', max_length=50)),
                ('gradient', models.CharField(default='linear-gradient(135deg,#6d6eb0,#a5a6dc)', max_length=255)),
                ('category', models.CharField(blank=True, default='', max_length=100)),
                ('tagline', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('overview', models.TextField(blank=True, default='')),
                ('what_it_does', models.TextField(blank=True, default='')),
                ('who_for', models.TextField(blank=True, default='')),
                ('original_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('our_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('duration', models.CharField(default='per month', max_length=100)),
                ('benefits', models.JSONField(blank=True, default=list)),
                ('features', models.JSONField(blank=True, default=list)),
                ('advantages', models.JSONField(blank=True, default=list)),
                ('use_cases', models.JSONField(blank=True, default=list)),
                ('plans', models.JSONField(blank=True, default=list)),
                ('faqs', models.JSONField(blank=True, default=list)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image_url', models.CharField(blank=True, default='', max_length=500)),
                ('logo_url', models.CharField(blank=True, default='', max_length=500)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('categories', models.JSONField(blank=True, default=list)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('post_link', models.CharField(blank=True, default='', max_length=500)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
